// This fetches REAL data from git_log.json (generated by Python script)
let auditData = [];

fetch('git_log.json')
  .then(response => response.json())
  .then(data => {
    auditData = data;
    buildDashboard();
    buildAuditTable(auditData);
    buildStatusTable();
    buildContributors();
    buildFilter();
  })
  .catch(() => {
    // If git_log.json not found yet, show a message
    document.getElementById('audit-body').innerHTML = `
      <tr>
        <td colspan="7" style="text-align:center; padding:40px; color:#718096;">
          ⚠️ No audit data yet. Run <strong>python generate_log.py</strong> in your terminal first!
        </td>
      </tr>
    `;
    document.getElementById('status-body').innerHTML = `
      <tr>
        <td colspan="6" style="text-align:center; padding:40px; color:#718096;">
          ⚠️ No data yet. Run the Python script first!
        </td>
      </tr>
    `;
  });

// ── Build dashboard counts ──────────────────────────────
function buildDashboard() {
  const authors = [...new Set(auditData.map(d => d.author))];
  const files   = [...new Set(auditData.flatMap(d => d.files))];

  document.getElementById('total-commits').textContent      = auditData.length;
  document.getElementById('total-contributors').textContent = authors.length;
  document.getElementById('total-files').textContent        = files.length;
  document.getElementById('total-audits').textContent       = auditData.length;
}

// ── Build audit log table ───────────────────────────────
function buildAuditTable(data) {
  const tbody = document.getElementById('audit-body');
  tbody.innerHTML = '';

  data.forEach((row, i) => {
    const tr = document.createElement('tr');
    tr.innerHTML = `
      <td>${i + 1}</td>
      <td><span class="commit-id">${row.id}</span></td>
      <td>${row.author}</td>
      <td>${row.date}</td>
      <td>${row.message}</td>
      <td>${row.files.join(', ')}</td>
      <td><span class="badge badge-${row.status}">${row.status}</span></td>
    `;
    tbody.appendChild(tr);
  });
}

// ── Build status accounting table ──────────────────────
function buildStatusTable() {
  const tbody   = document.getElementById('status-body');
  const fileMap = {};

  // CI type mapping
  const ciTypes = {
    'index.html':       'Source Code',
    'style.css':        'Source Code',
    'script.js':        'Source Code',
    'generate_log.py':  'Build Script',
    'README.md':        'Documentation',
    'git_log.json':     'Documentation',
    '.gitignore':       'Config File'
  };

  auditData.forEach(commit => {
    commit.files.forEach(file => {
      if (!fileMap[file]) {
        fileMap[file] = {
          lastAuthor: '',
          lastDate:   '',
          major:      1,
          minor:      0,
          changes:    0
        };
      }
      fileMap[file].lastAuthor = commit.author;
      fileMap[file].lastDate   = commit.date;
      fileMap[file].changes   += 1;

      // Version logic: every 3 small changes = major bump
      fileMap[file].minor += 1;
      if (fileMap[file].minor > 2) {
        fileMap[file].major += 1;
        fileMap[file].minor  = 0;
      }
    });
  });

  tbody.innerHTML = '';
  Object.entries(fileMap).forEach(([file, info]) => {
    const ciType  = ciTypes[file] || 'Other';
    const version = `v${info.major}.${info.minor}`;

    // State logic
    let state     = 'Stable';
    let stateBadge = 'badge-stable';
    if (info.changes === 1) {
      state      = 'Baseline';
      stateBadge = 'badge-source';
    } else if (info.changes >= 3) {
      state      = 'Modified';
      stateBadge = 'badge-modified';
    }

    const tr = document.createElement('tr');
    tr.innerHTML = `
      <td>${file}</td>
      <td>${info.lastAuthor}</td>
      <td>${info.lastDate}</td>
      <td>${version}</td>
      <td>${info.changes}</td>
      <td><span class="badge badge-doc">${ciType}</span></td>
      <td><span class="badge ${stateBadge}">${state}</span></td>
    `;
    tbody.appendChild(tr);
  });
}

// ── Build contributor cards ─────────────────────────────
function buildContributors() {
  const authorMap = {};

  auditData.forEach(commit => {
    if (!authorMap[commit.author]) {
      authorMap[commit.author] = { email: commit.email, commits: 0 };
    }
    authorMap[commit.author].commits += 1;
  });

  const container = document.getElementById('contributor-cards');
  container.innerHTML = '';

  Object.entries(authorMap).forEach(([name, info]) => {
    const initials = name.split(' ').map(n => n[0]).join('').toUpperCase();
    const card = document.createElement('div');
    card.className = 'contributor-card';
    card.innerHTML = `
      <div class="contributor-avatar">${initials}</div>
      <div class="contributor-name">${name}</div>
      <div class="contributor-email">${info.email}</div>
      <div class="contributor-commits">${info.commits}</div>
      <div class="contributor-commits-label">Total Commits</div>
    `;
    container.appendChild(card);
  });
}

// ── Populate author filter dropdown ────────────────────
function buildFilter() {
  const authors = [...new Set(auditData.map(d => d.author))];
  const select  = document.getElementById('filter-author');

  authors.forEach(author => {
    const opt = document.createElement('option');
    opt.value       = author;
    opt.textContent = author;
    select.appendChild(opt);
  });
}

// ── Search + filter logic ───────────────────────────────
document.getElementById('search').addEventListener('input', applyFilters);
document.getElementById('filter-author').addEventListener('change', applyFilters);

function applyFilters() {
  const query  = document.getElementById('search').value.toLowerCase();
  const author = document.getElementById('filter-author').value;

  const filtered = auditData.filter(row => {
    const matchSearch = !query ||
      row.author.toLowerCase().includes(query)  ||
      row.message.toLowerCase().includes(query) ||
      row.files.some(f => f.toLowerCase().includes(query));

    const matchAuthor = !author || row.author === author;
    return matchSearch && matchAuthor;
  });

  buildAuditTable(filtered);
}